export const data = [
  {
    model: "Experiment ID -AD-1145",
    project_type: "Lorem lpsum",
    project_name: "Lorem lpsum",
    status: "In progress",
    view: true,
    validate: true,
    validate: true,
  },
  {
    model: "Experiment ID -AD-1145",
    project_type: "Lorem lpsum",
    project_name: "Lorem lpsum",
    status: "In progress",
    view: true,
    validate: false,
    retrain: false,
  },
  {
    model: "Experiment ID -BX-3289",
    project_type: "Drug Discovery",
    project_name: "Cancer Cell Inhibition",
    status: "Failed",
    view: true,
    validate: false,
  },
  {
    model: "Experiment ID -ZM-4511",
    project_type: "Genomics",
    project_name: "DNA Mapping",
    status: "Complete",
    view: false,
    validate: true,
    retrain: true,
  },
  {
    model: "Experiment ID -HY-7832",
    project_type: "Proteomics",
    project_name: "Protein Folding Study",
    status: "In progress",
    view: true,
    validate: false,
    retrain: false,
  },
  {
    model: "Experiment ID -LP-2291",
    project_type: "Neuroscience",
    project_name: "Brain Signal Mapping",
    status: "Complete",
    view: true,
    validate: true,
  },
  {
    model: "Experiment ID -KR-0023",
    project_type: "Toxicology",
    project_name: "Chemical Resistance Study",
    status: "In progress",
    view: false,
    validate: true,
    retrain: false,
  },
  {
    model: "Experiment ID -QX-7281",
    project_type: "Genomics",
    project_name: "Genome Alignment",
    status: "In progress",
    view: true,
    validate: false,
  },
  {
    model: "Experiment ID -PL-4492",
    project_type: "Proteomics",
    project_name: "Enzyme Reaction Study",
    status: "Failed",
    view: true,
    validate: true,
    retrain: true,
  },
  {
    model: "Experiment ID -XZ-3001",
    project_type: "Neuroscience",
    project_name: "Neuron Firing Analysis",
    status: "Complete",
    view: false,
    validate: true,
  },
  {
    model: "Experiment ID -LA-9940",
    project_type: "Drug Discovery",
    project_name: "Anti-Viral Trials",
    status: "Failed",
    view: true,
    validate: false,
    retrain: false,
  },
  {
    model: "Experiment ID -VD-1308",
    project_type: "Toxicology",
    project_name: "Heavy Metal Resistance",
    status: "In progress",
    view: false,
    validate: true,
    retrain: true,
  },
  {
    model: "Experiment ID -KM-2193",
    project_type: "Cell Biology",
    project_name: "Stem Cell Growth",
    status: "Complete",
    view: true,
    validate: true,
  },
  {
    model: "Experiment ID -FB-7200",
    project_type: "Genomics",
    project_name: "Mutation Tracking",
    status: "In progress",
    view: false,
    validate: false,
  },
  {
    model: "Experiment ID -JT-3384",
    project_type: "Immunology",
    project_name: "Vaccine Response",
    status: "Failed",
    view: true,
    validate: false,
    retrain: true,
  },
  {
    model: "Experiment ID -NP-5522",
    project_type: "Neuroscience",
    project_name: "Cognitive Function Imaging",
    status: "Complete",
    view: true,
    validate: true,
  },
  {
    model: "Experiment ID -WL-8847",
    project_type: "Proteomics",
    project_name: "Protein Synthesis Rate",
    status: "In progress",
    view: false,
    validate: true,
    retrain: false,
  },
  {
    model: "Experiment ID -UR-4312",
    project_type: "Drug Discovery",
    project_name: "Pain Receptor Blockers",
    status: "Complete",
    view: true,
    validate: false,
  },
  {
    model: "Experiment ID -CS-8430",
    project_type: "Genomics",
    project_name: "RNA Splicing",
    status: "Failed",
    view: false,
    validate: false,
    retrain: true,
  },
  {
    model: "Experiment ID -DY-2390",
    project_type: "Toxicology",
    project_name: "Pesticide Impact",
    status: "In progress",
    view: true,
    validate: true,
  },
  {
    model: "Experiment ID -TH-6715",
    project_type: "Cell Biology",
    project_name: "Mitochondrial Activity",
    status: "Complete",
    view: false,
    validate: true,
    retrain: false,
  },
  {
    model: "Experiment ID -RM-1024",
    project_type: "Immunology",
    project_name: "T-cell Response Study",
    status: "Failed",
    view: true,
    validate: false,
  },
];

export function fetchAnnotationsSimulation() {
  return new Promise((resolve) => {
    const mockResponse = {
      ai_model_name: "Model11",
      project_name: "newProject111",
      bucket_name: "",
      folder_name: "",
      classname: ["Class_1", "Class_2", "Class_3", "Class_4"],
      annotations: {
        "4482736.png": [
          [169, 87.90625, 229, 154.90625, 0],
          [243, 121.90625, 303, 171.90625, 1],
          [169, 87.90625, 229, 154.90625, 2],
          [243, 121.90625, 303, 171.90625, 3],
        ],
        "4482741.png": [
          [169, 87.90625, 229, 154.90625, 0],
          [243, 121.90625, 303, 171.90625, 1],
          [169, 87.90625, 229, 154.90625, 2],
          [243, 121.90625, 303, 171.90625, 3],
        ],
      },
    };

    const result = {};

    for (const [filename, boxes] of Object.entries(mockResponse.annotations)) {
      result[filename] = boxes.map(([x1, y1, x2, y2, classIndex]) => ({
        x1,
        y1,
        x2,
        y2,
        class:  Math.floor(Math.random() * 5),
      }));
    }
    
    setTimeout(() => resolve(result), 500); // Simulate latency
  });
}
